[versions]

fabric-loader = "0.17.3"
fabric-language-kotlin = "1.13.6+kotlin.2.2.20"

skyblockapi = "3.0.10"
repo-lib = "3.0.2"
devauth = "1.2.1"

ksp = "2.2.10-2.0.2"
meowdding-resources = "1.0.15"

rconfigkt = "3.5.15"

gson = "2.12.1"
meowdding-ktmodules = "1.0.5"
meowdding-ktcodecs = "1.1.0"
meowdding-lib = "3.0.13"

[libraries]

fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

skyblockapi = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblockapi" }
repo-lib = { module = "tech.thatgravyboat.repo-lib:repo-lib", version.ref = "repo-lib" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

resourceful-config-kotlin = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-fabric-1.21.5", version.ref = "rconfigkt" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
meowdding-resources = { module = "me.owdding.repo:compacting-resources", version.ref = "meowdding-resources" }
meowdding-ktmodules = { module = "me.owdding.ktmodules:KtModules", version.ref = "meowdding-ktmodules" }
meowdding-ktcodecs = { module = "me.owdding.ktcodecs:KtCodecs", version.ref = "meowdding-ktcodecs" }
meowdding-lib = { module = "me.owdding.meowdding-lib:meowdding-lib", version.ref = "meowdding-lib" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
